//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySlipGeneration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaySlipGeneration.ConfigErrorMessage", typeof(ConfigErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect configuration file format (XML file)..
        /// </summary>
        internal static string BAD_CONFIG_FILE {
            get {
                return ResourceManager.GetString("BAD_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find configuration XML file at specified location/Incorrect address..
        /// </summary>
        internal static string CONF_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CONF_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\MyProject\PaySlipGeneration\PaySlipGeneration\bin\XMLFile1.xml.
        /// </summary>
        internal static string CONFIG_FILE_PATH {
            get {
                return ResourceManager.GetString("CONFIG_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not correct..
        /// </summary>
        internal static string DATA_FORMAT {
            get {
                return ResourceManager.GetString("DATA_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sending fail..
        /// </summary>
        internal static string EMAIL_SEND_FAIL {
            get {
                return ResourceManager.GetString("EMAIL_SEND_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent successfully..
        /// </summary>
        internal static string EMAIL_SEND_SUCCESS {
            get {
                return ResourceManager.GetString("EMAIL_SEND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email id not found, mail sending fail..
        /// </summary>
        internal static string EMAILID_NOT_FOUND {
            get {
                return ResourceManager.GetString("EMAILID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee dosenot exist to send mail..
        /// </summary>
        internal static string EMPLOYEE_DOESNOT_EXIST {
            get {
                return ResourceManager.GetString("EMPLOYEE_DOESNOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while uploading a file.
        /// </summary>
        internal static string ERROR_UPLOADING {
            get {
                return ResourceManager.GetString("ERROR_UPLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file not found.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment file size should not be greater then 1 MB!.
        /// </summary>
        internal static string FILE_SIZE {
            get {
                return ResourceManager.GetString("FILE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required tags in configuration file are missing.
        /// </summary>
        internal static string MORE_TAGS_NOT_FOUND {
            get {
                return ResourceManager.GetString("MORE_TAGS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple tags were found in configuration file.
        /// </summary>
        internal static string MULTIPLE_TAGS_FOUND {
            get {
                return ResourceManager.GetString("MULTIPLE_TAGS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to send mail..
        /// </summary>
        internal static string NO_DATA {
            get {
                return ResourceManager.GetString("NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are No Rows in this File!!!.
        /// </summary>
        internal static string NO_ROW_FOUND {
            get {
                return ResourceManager.GetString("NO_ROW_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file to upload..
        /// </summary>
        internal static string SELECT_FILE {
            get {
                return ResourceManager.GetString("SELECT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull..
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload only Excel.
        /// </summary>
        internal static string UPLOAD_XML {
            get {
                return ResourceManager.GetString("UPLOAD_XML", resourceCulture);
            }
        }
    }
}
